<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gbt_driver</name>
  <version>0.1.0</version>
  <description>Agilebot Robot ROS2 Driver </description>
  <maintainer email="info@agilebot.com.cn">Agilebot</maintainer>
  <license>BSD-3-Clause</license>

  <!--tool package -->
  <exec_depend>common</exec_depend>  
  <!-- interface package -->
  <exec_depend>gbt_interface</exec_depend>



  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>launch_testing</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
